name: "dbt_vault_retail"
version: "1.0.0"
config-version: 2

profile: "retail_vault"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  dbt_vault_retail:

    staging:
      +schema: stg
      +materialized: view

    raw_vault:
      +schema: raw_vault
      +materialized: incremental

      hubs:
        +tags: ["raw_vault", "hub"]

      links:
        +tags: ["raw_vault", "link"]

      sats:
        +tags: ["raw_vault", "sat"]

    buisness_vault:
      +schema: business_vault
      +materialized: incremental

      sats:
        +tags: ["business_vault", "sat"]

      pit:
        +tags: ["business_vault", "pit"]

      bridges:
        +tags: ["business_vault", "bridge"]

    marts:
      +schema: mart
      +materialized: table

      dim:
        +tags: ["mart", "dimension"]

      fct:
        +tags: ["mart", "fact"]

seeds:
  dbt_vault_retail:
    +schema: seed
