retail_vault:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy_account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy_password') }}" # nosec
      role: "{{ env_var('SNOWFLAKE_ROLE', 'dummy_role') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'dummy_warehouse') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'dummy_db') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'dummy_schema') }}"
      threads: 6
      client_session_keep_alive: False
