retail_vault:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'parse_only') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'parse_only') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'parse_only') }}" # nosec
      role: "{{ env_var('SNOWFLAKE_ROLE', 'parse_only') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'parse_only') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'parse_only') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'parse_only') }}"
      threads: 6
      client_session_keep_alive: False
